# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1db085f80dfc162e6cdb2866689cfedba14aeaa105a4d5812d4d0d786a55e327f3871a07bb7a9391a1ef13fb5c47702bb99332c9d89702425191ba975626e16f

test:
  secret_key_base: d55b9f2aa18373164d730111d2d36b95052cc24a553c69bdb7ea5d0abc1e6cc105108ff7e1f84470dbeb6d2a95bc1f834bf54f8baf588ab65c11eaaadd7705b3

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
